name: mod
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.13
  - pytorch=2.4.* 
  - pandas=2.3.1
  - scikit-learn
  - pip
  - pip:
      - streamlit==1.49.1
      - transformers==4.55.2
      - accelerate==1.10.0
      - evaluate==0.4.5
